# Site settings
title: "Data Portfolio"
description: "This is my portfolio website! ğŸŒŸ"
baseurl: "/youtuber_uk" # TÃªn repo cá»§a báº¡n
url: "https://badguyIT.github.io" # Äá»‹a chá»‰ URL cá»§a GitHub Pages

# Author settings
author:
  name: "badguyIT"
  email: "badguyit25@gmail.com"
  avatar: "path/to/your/avatar.jpg" # ÄÆ°á»ng dáº«n tá»›i hÃ¬nh Ä‘áº¡i diá»‡n cá»§a báº¡n

# Theme settings
remote_theme: "pages-themes/modernist@v0.2.0" # Sá»­ dá»¥ng theme Modernist tá»« GitHub Pages
plugins:
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-include-cache

# Header and navigation links
header_pages:
  - index.md
  - about.md
  - projects.md

# Build settings
markdown: kramdown

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Social media links
social:
  github: badguyIT

# Footer settings
footer:
  # Footer text
  text: "Maintained by [badguyIT](https://github.com/badguyIT). Generated by GitHub Pages using the [Modernist](https://github.com/pages-themes/modernist) theme."

# Links to other pages or resources
links:
  - title: "View on GitHub"
    url: "https://github.com/badguyIT/youtuber_uk"
    icon: "fab fa-github"
  - title: "Download .zip"
    url: "https://github.com/badguyIT/youtuber_uk/archive/refs/heads/main.zip"
    icon: "fas fa-file-archive"
  - title: "Download .tar.gz"
    url: "https://github.com/badguyIT/youtuber_uk/archive/refs/heads/main.tar.gz"
    icon: "fas fa-file-archive"
